# Settings for ros_control control loop
hardware_control_loop:
   loop_hz: &loop_hz 500

# Settings for ros_control hardware interface
ur_hardware_interface:
   joints: &robot_arm_joints
     - $(arg prefix)arm_shoulder_pan_joint
     - $(arg prefix)arm_shoulder_lift_joint
     - $(arg prefix)arm_elbow_joint
     - $(arg prefix)arm_wrist_1_joint
     - $(arg prefix)arm_wrist_2_joint
     - $(arg prefix)arm_wrist_3_joint

# Publish all joint states ----------------------------------
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: *loop_hz

# Publish wrench ----------------------------------
force_torque_sensor_controller:
   type:         force_torque_sensor_controller/ForceTorqueSensorController
   publish_rate: *loop_hz

# Publish speed_scaling factor
speed_scaling_state_controller:
   type:         scaled_controllers/SpeedScalingStateController
   publish_rate: *loop_hz

# Joint Trajectory Controller - position based -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
scaled_pos_traj_controller:
   type: position_controllers/ScaledJointTrajectoryController
   joints: *robot_arm_joints
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      $(arg prefix)arm_shoulder_pan_joint: {trajectory: 0.2, goal: 0.1}
      $(arg prefix)arm_shoulder_lift_joint: {trajectory: 0.2, goal: 0.1}
      $(arg prefix)arm_elbow_joint: {trajectory: 0.2, goal: 0.1}
      $(arg prefix)arm_wrist_1_joint: {trajectory: 0.2, goal: 0.1}
      $(arg prefix)arm_wrist_2_joint: {trajectory: 0.2, goal: 0.1}
      $(arg prefix)arm_wrist_3_joint: {trajectory: 0.2, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate: *loop_hz
   action_monitor_rate: 10

pos_traj_controller:
   type: position_controllers/JointTrajectoryController
   joints: *robot_arm_joints
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      $(arg prefix)arm_shoulder_pan_joint: {trajectory: 0.2, goal: 0.1}
      $(arg prefix)arm_shoulder_lift_joint: {trajectory: 0.2, goal: 0.1}
      $(arg prefix)arm_elbow_joint: {trajectory: 0.2, goal: 0.1}
      $(arg prefix)arm_wrist_1_joint: {trajectory: 0.2, goal: 0.1}
      $(arg prefix)arm_wrist_2_joint: {trajectory: 0.2, goal: 0.1}
      $(arg prefix)arm_wrist_3_joint: {trajectory: 0.2, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate: *loop_hz
   action_monitor_rate: 10
