controller_list:
  - name: fake_manipulator_controller
    type: $(arg execution_type)
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5
      - arm_joint_6
      - arm_joint_7
initial:  # Define initial robot poses.
#  - group: manipulator
#    pose: home

  []