arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - fr3_joint1
    - fr3_joint2
    - fr3_joint3
    - fr3_joint4
    - fr3_joint5
    - fr3_joint6
    - fr3_joint7
  gains:
    fr3_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fr3_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fr3_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fr3_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fr3_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fr3_joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fr3_joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1